package com.ca.europaclean.core.designsystem.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class EuropaCleanColors(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val inversePrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceTint: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val surfaceBright: Color,
    val surfaceDim: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainerLowest: Color,
    val primaryFixed: Color,
    val primaryFixedDim: Color,
    val onPrimaryFixed: Color,
    val onPrimaryFixedVariant: Color,
    val secondaryFixed: Color,
    val secondaryFixedDim: Color,
    val onSecondaryFixed: Color,
    val onSecondaryFixedVariant: Color,
    val tertiaryFixed: Color,
    val tertiaryFixedDim: Color,
    val onTertiaryFixed: Color,
    val onTertiaryFixedVariant: Color,
)

internal val EuropaCleanLightColors = EuropaCleanColors(
    primary = Ice40,
    onPrimary = White,
    primaryContainer = Ice90,
    onPrimaryContainer = Ice10,
    inversePrimary = Ice80,
    secondary = Stone40,
    onSecondary = White,
    secondaryContainer = Stone90,
    onSecondaryContainer = Stone10,
    tertiary = Copper40,
    onTertiary = White,
    tertiaryContainer = Copper90,
    onTertiaryContainer = Copper10,
    background = Neutral98,
    onBackground = Neutral10,
    surface = Neutral98,
    onSurface = Neutral10,
    surfaceVariant = NeutralVariant90,
    onSurfaceVariant = NeutralVariant30,
    surfaceTint = Ice40,
    inverseSurface = Neutral20,
    inverseOnSurface = Neutral95,
    error = Error40,
    onError = White,
    errorContainer = Error90,
    onErrorContainer = Error10,
    outline = NeutralVariant50,
    outlineVariant = NeutralVariant80,
    scrim = Black,
    surfaceBright = Neutral98,
    surfaceContainer = Neutral94,
    surfaceContainerHigh = Neutral92,
    surfaceContainerHighest = Neutral90,
    surfaceContainerLow = Neutral96,
    surfaceContainerLowest = White,
    surfaceDim = Neutral87,
    primaryFixed = Ice90,
    primaryFixedDim = Ice80,
    onPrimaryFixed = Ice10,
    onPrimaryFixedVariant = Ice30,
    secondaryFixed = Stone90,
    secondaryFixedDim = Stone80,
    onSecondaryFixed = Stone10,
    onSecondaryFixedVariant = Stone30,
    tertiaryFixed = Copper90,
    tertiaryFixedDim = Copper80,
    onTertiaryFixed = Copper10,
    onTertiaryFixedVariant = Copper30,
)

internal val EuropaCleanDarkColors = EuropaCleanColors(
    primary = Ice80,
    onPrimary = Ice20,
    primaryContainer = Ice30,
    onPrimaryContainer = Ice90,
    inversePrimary = Ice40,
    secondary = Stone80,
    onSecondary = Stone20,
    secondaryContainer = Stone30,
    onSecondaryContainer = Stone90,
    tertiary = Copper80,
    onTertiary = Copper20,
    tertiaryContainer = Copper30,
    onTertiaryContainer = Copper90,
    background = Neutral6,
    onBackground = Neutral90,
    surface = Neutral6,
    onSurface = Neutral90,
    surfaceVariant = NeutralVariant30,
    onSurfaceVariant = NeutralVariant80,
    surfaceTint = Ice80,
    inverseSurface = Neutral90,
    inverseOnSurface = Neutral20,
    error = Error80,
    onError = Error20,
    errorContainer = Error30,
    onErrorContainer = Error90,
    outline = NeutralVariant60,
    outlineVariant = NeutralVariant30,
    scrim = Black,
    surfaceBright = Neutral24,
    surfaceContainer = Neutral12,
    surfaceContainerHigh = Neutral17,
    surfaceContainerHighest = Neutral22,
    surfaceContainerLow = Neutral10,
    surfaceContainerLowest = Neutral4,
    surfaceDim = Neutral6,
    primaryFixed = Ice90,
    primaryFixedDim = Ice80,
    onPrimaryFixed = Ice10,
    onPrimaryFixedVariant = Ice30,
    secondaryFixed = Stone90,
    secondaryFixedDim = Stone80,
    onSecondaryFixed = Stone10,
    onSecondaryFixedVariant = Stone30,
    tertiaryFixed = Copper90,
    tertiaryFixedDim = Copper80,
    onTertiaryFixed = Copper10,
    onTertiaryFixedVariant = Copper30,
)

internal val LocalEuropaCleanColors = staticCompositionLocalOf<EuropaCleanColors> {
    error("No EuropaCleanColors provided")
}
